server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
#        native:
#          searchLocations: classpath:/configs/{application}
        git:
          uri: https://VitalyMykush/spring-cloud-netflix-microservices/config-repo
          clone-on-start: true
          name: VitalyMykush
          password: 20102А20102а
