server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/configs/{application}
        git:
          uri: https://github.com/VitalyMykush/spring-cloud-netflix-microservices/
          clone-on-start: true
          default-label: main
          search-paths: "config-repo/{application}"
          name: VitalyMykush
          password: 20102А20102а
          skipSslValidation: true

